import React from "react";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};
export default function RootLayout({ children: children, React }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`${inter.className} bg-dark-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}

// import React from "react";
// import { ClerkProvider } from "@clerk/nextjs";
// import "../globals.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className="bg-dark-1">{children}</body>
//       </html>
//     </ClerkProvider>
//   );
// }
